config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from fight_covid19.maps import views as map_views

urlpatterns = [
    path("", map_views.HomePageView, name="home"),
    path("maps/", include(("fight_covid19.maps.urls", "maps"), namespace="maps")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path("maps/", TemplateView.as_view(template_name="maps/maps.html"), name="maps"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("fight_covid19.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("news/", include(("fight_covid19.news.urls", "news"), namespace="news")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

fight_covid19/maps/urls.py
from django.urls import path
from fight_covid19.maps import views as map_views
from django.views.generic import TemplateView


urlpatterns = [
    path("", TemplateView.as_view(template_name="maps/maps.html"), name="home"),
    path("health_form/", map_views.HealthFormView, name="health_form"),
    path("map_markers/", map_views.MapMarkersView, name="map_markers"),
    path("my_health", map_views.MyHealthView, name="my_health"),
    path("patients_nearme", map_views.NearCount.as_view(), name="near_count"),
    path(
        "oneshot_health_entry",
        TemplateView.as_view(template_name="maps/one_shot_health_form.html"),
        name="oneshot_health_entry",
    ),
    path(
        "help_entry",
        TemplateView.as_view(template_name="maps/help_entry_form.html"),
        name="health_entry",
    ),
    path(
        "generate_unique_key",
        map_views.GenerateUniqueKey.as_view(),
        name="generate_unique_key",
    ),
    path(
        "oneshot_form_entry",
        map_views.OneShotFormEntry.as_view(),
        name="oneshot_form_entry",
    ),
]

fight_covid19/news/urls.py
from django.urls import path
from fight_covid19.news import views

urlpatterns = [
    path("", views.index, name="index"),
]

fight_covid19/users/urls.py
from django.urls import path

from fight_covid19.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

fight_covid19/news/models.py
from django.db import models

# Create your models here.

fight_covid19/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

fight_covid19/api/coronacases/views.py
from django.core.cache import cache
from rest_framework import viewsets
from rest_framework.response import Response

from fight_covid19.maps.helpers import get_covid19_stats


class CoronaVirusCasesViewSet(viewsets.ViewSet):
    def list(self, request, *args, **kwargs):
        covid19_stats = cache.get("covid19_stats", default=None)
        if not covid19_stats:
            covid19_stats = get_covid19_stats()
        return Response(covid19_stats)

fight_covid19/api/hoi/views.py
import datetime

from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.db import transaction
from django.utils import timezone
from rest_framework import viewsets
from rest_framework.response import Response

from fight_covid19.maps.helpers import get_hoi_stats
from fight_covid19.maps.models import HealthEntry
from .serializers import HealthEntrySerializer, HealthEntryFormSerializer

User = get_user_model()


class HealthEntryViewSet(viewsets.ModelViewSet):
    """API endpoints for the Health Entry Statistics"""

    queryset = HealthEntry.objects.all()
    serializer_class = HealthEntrySerializer

    def create(self, request, *args, **kwargs):
        entryform_serializer = HealthEntryFormSerializer(
            data=request.data, context={"request": request}
        )
        if entryform_serializer.is_valid():
            try:
                # Atomic transaction
                with transaction.atomic():
                    entry_form = entryform_serializer.save()
                    entry_form.creation_timestamp = datetime.datetime.now(
                        tz=timezone.utc
                    )
                    entry_form.save()
            except Exception as e:
                return Response({"error": str(e)})
            resp = HealthEntrySerializer(entry_form)
            return Response(resp.data)

            # If there are errors, return them
        else:
            errors = dict()
            entryform_serializer.is_valid()
            errors.update(dict(entryform_serializer.errors))
            return Response(errors)


class HealthStatisticsViewSet(viewsets.ViewSet):
    def list(self, request, *args, **kwargs):
        hoi_stats = cache.get("hoi_stats", default=None)
        if not hoi_stats:
            hoi_stats = get_hoi_stats()
        return Response(hoi_stats)

fight_covid19/api/news/views.py
from django.core.cache import cache
from rest_framework import viewsets
from rest_framework.response import Response

from fight_covid19.news.helpers import get_news


class NewsViewSet(viewsets.ViewSet):
    def list(self, request, *args, **kwargs):
        news_dict = cache.get("news", default=None)
        if not news_dict:
            news_dict = get_news()
        return Response(news_dict)

fight_covid19/api/users/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from fight_covid19.api.users.serializers import UserSerializer

User = get_user_model()


class UserViewSet(viewsets.ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"
    # def get_queryset(self, *args, **kwargs):
    #     return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

    @action(detail=False, methods=["GET"])
    def current_user(self, request):
        try:
            user_query = User.objects.all().get(user=request.user)
            serialized_user = UserSerializer(user_query, context={"request": request})
        except:
            serialized_user = UserSerializer(request.user, context={"request": request})
        return Response(serialized_user.data)

fight_covid19/maps/api/views.py
import datetime

from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.db import transaction
from django.utils import timezone
from rest_framework import viewsets
from rest_framework.response import Response

from fight_covid19.maps.helpers import get_covid19_stats, get_hoi_stats
from fight_covid19.maps.models import HealthEntry
from .serializers import HealthEntrySerializer, HealthEntryFormSerializer

User = get_user_model()


class HealthEntryViewSet(viewsets.ModelViewSet):
    """API endpoints for the Health Entry Statistics"""

    queryset = HealthEntry.objects.all()
    serializer_class = HealthEntrySerializer

    def create(self, request, format=None, *args, **kwargs):
        entryform_serializer = HealthEntryFormSerializer(
            data=request.data, context={"request": request}
        )
        if entryform_serializer.is_valid():
            try:
                # Atomic transaction
                with transaction.atomic():
                    entry_form = entryform_serializer.save()
                    entry_form.user = User.objects.get(pk=request.data["user_id"])
                    entry_form.creation_timestamp = datetime.datetime.now(
                        tz=timezone.utc
                    )
                    entry_form.save()
            except Exception as e:
                return Response({"error": str(e)})
            resp = HealthEntrySerializer(entry_form)
            return Response(resp.data)

            # If there are errors, return them
        else:
            errors = dict()
            HealthEntryFormSerializer.is_valid()
            errors.update(dict(HealthEntryFormSerializer.errors))
            return Response(errors)


class CoronaVirusCasesViewSet(viewsets.ViewSet):
    def list(self, request, *args, **kwargs):
        data = dict()
        covid19_stats = cache.get("covid19_stats", default=None)
        if not covid19_stats:
            covid19_stats = get_covid19_stats()
        data["total"] = covid19_stats["total_stats"]
        data["last_updated"] = covid19_stats["tests_performed"]
        data["statewise"] = covid19_stats["statewise"]
        return Response(data)


class HealthStatisticsViewSet(viewsets.ViewSet):
    def list(self, request, *args, **kwargs):
        hoi_stats = cache.get("hoi_stats", default=None)
        if not hoi_stats:
            hoi_stats = get_hoi_stats()
        return Response(hoi_stats)

fight_covid19/maps/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
import json
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic import View
from django.views.generic.edit import FormView
from django.db.models import Count
from geopy.geocoders import Nominatim

from fight_covid19.maps import forms
from fight_covid19.maps.helpers import (
    get_covid19_stats,
    get_hoi_stats,
    get_map_markers,
    get_range_coords,
)
from fight_covid19.maps.models import HealthEntry
from fight_covid19.maps.models import HelpEntry
from fight_covid19.maps.models import KeyValuePair


class HomePage(View):
    def get(self, request, *args, **kwargs):
        covid19_stats = cache.get("covid19_stats", default=None)
        hoi_stats = cache.get("hoi_stats", default=None)
        if not covid19_stats:
            covid19_stats = get_covid19_stats()
        if not hoi_stats:
            hoi_stats = get_hoi_stats()

        # else:
        #     total, statewise, last_updated = c
        return render(
            request,
            "pages/home.html",
            context={"covid19_stats": covid19_stats, "hoi_stats": hoi_stats},
        )


HomePageView = HomePage.as_view()


class HealthForm(LoginRequiredMixin, FormView):
    form_class = forms.HealthEntryForm
    template_name = "maps/health_form.html"
    success_url = reverse_lazy("maps:my_health")

    def form_valid(self, form):
        if form.is_valid():
            entry = form.save(commit=False)
            entry.user = self.request.user
            entry.save()

        return super().form_valid(form)


HealthFormView = HealthForm.as_view()


class MyHealth(LoginRequiredMixin, ListView):
    model = HealthEntry
    template_name = "maps/my_health.html"
    context_object_name = "entries"

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user).order_by(
            "-creation_timestamp"
        )


MyHealthView = MyHealth.as_view()


class MapMarkers(View):
    def get(self, request, *args, **kwargs):
        points_list = cache.get("map_markers", default=None)
        if not points_list:
            points_list = get_map_markers()
        return JsonResponse(points_list, safe=False)


MapMarkersView = MapMarkers.as_view()


class NearCount(View):
    def get(self, request, *args, **kwargs):
        ranges = get_range_coords(
            float(request.GET.get("latitude")),
            float(request.GET.get("longitude")),
            float(request.GET.get("distance", 5)),
        )

        total_count = (
            HealthEntry.objects.all()
            .filter(
                latitude__range=(ranges["min_lat"], ranges["max_lat"]),
                longitude__range=(ranges["min_lon"], ranges["max_lon"]),
            )
            .values("user_id")
            .annotate(total=Count("user_id"))
            .count()
        )

        """TO get the location of the people by coordinates"""
        geolocator = Nominatim(user_agent="Health of India")
        location = geolocator.reverse(
            "{0}, {1}".format(request.GET.get("latitude"), request.GET.get("longitude"))
        )
        address = location.address

        data = dict()
        data["address"] = address
        data["total"] = total_count
        return JsonResponse(data)


class GenerateUniqueKey(View):
    def get(self, request, *args, **kwargs):
        try:
            counter = KeyValuePair.objects.get(name="unique_key_counter")
        except KeyValuePair.DoesNotExist:
            counter = KeyValuePair.objects.create(name="unique_key_counter", value="1")

        unique_id = counter.value

        # Updating values
        counter.value = str(int(counter.value) + 1)
        counter.save()

        return JsonResponse({"id": unique_id})


class OneShotFormEntry(View):
    def post(self, request, *args, **kwargs):
        raw_data = request.body.decode("utf-8")
        form_data = json.loads(raw_data)
        HealthEntry.objects.create(
            age=form_data["age"],
            gender=form_data["gender"],
            fever=form_data["fever"],
            cough=form_data["cough"],
            difficult_breathing=form_data["difficult_breathing"],
            self_quarantine=form_data["quarantine"],
            latitude=form_data["latitude"],
            longitude=form_data["longitude"],
            unique_id=form_data["unique_id"],
        )
        return JsonResponse({"status": "success"})


class HelpEntryForm(View):
    def post(self, request, *args, **kwargs):
        raw_data = request.body.decode("utf-8")
        form_data = json.loads(raw_data)
        HelpEntry.objects.create(
            fullname=form_data["fullname"],
            phone_number=form_data["phone_number"],
            help_type=form_data["help_type"],
            address=form_data["address"],
            description=form_data["description"],
            latitude=form_data["latitude"],
            longitude=form_data["longitude"],
        )
        return JsonResponse({"status": "success"})

fight_covid19/news/views.py
from django.shortcuts import render
from newsapi import NewsApiClient
from django.core.cache import cache
from fight_covid19.news.helpers import get_news


def index(request):
    news_dict = cache.get("news", default=None)
    if not news_dict:
        news_dict = get_news()
    return render(request, "news/news.html", context={"news_dict": news_dict})

fight_covid19/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(viewsets.ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"
    # def get_queryset(self, *args, **kwargs):
    #     return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

    @action(detail=False, methods=["GET"])
    def current_user(self, request):
        try:
            user_query = User.objects.all().get(user=request.user)
            serialized_user = UserSerializer(user_query, context={"request": request})
        except:
            serialized_user = UserSerializer(request.user, context={"request": request})
        return Response(serialized_user.data)

fight_covid19/templates/base-uikit.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Fight Covid19{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="An initiative to gauage  Health of Citizens in India to fight against Covid19.">
  <meta name="author" content="Health of India">

  <meta property="og:description" content="An initiative to gauage  Health of Citizens in India to fight against Covid19." />
  <meta property="og:url" content="https://covid19.thepodnet.com/" />
  <meta property="og:title" content="Health of India" />
  <meta property="og:image" content="https://covid19.thepodnet.com{% static 'images/favicons/500_500.jpg' %}" />
  <meta property="og:image:type" content="image/jpeg" />
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
  <![endif]-->
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicons/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png' %}">
  <link href="https://fonts.googleapis.com/css?family=Raleway:900&display=swap" rel="stylesheet">
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-162832950-1"></script>
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <script src="{% static 'js/wow.min.js' %}"></script>
  <script>
    new WOW().init();
  </script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());
    gtag('config', 'UA-162832950-1');
  </script>
  <script>
    document.addEventListener('DOMContentLoaded', () => {

      // Get all "navbar-burger" elements
      const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

      // Check if there are any navbar burgers
      if ($navbarBurgers.length > 0) {

        // Add a click event on each of them
        $navbarBurgers.forEach(el => {
          el.addEventListener('click', () => {

            // Get the target from the "data-target" attribute
            const target = el.dataset.target;
            const $target = document.getElementById(target);

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            el.classList.toggle('is-active');
            $target.classList.toggle('is-active');

          });
        });
      }

    });
  </script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

  <!-- UIkit CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  <link href="{% static 'css/spacing.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Exo+2:wght@300;600&display=swap" rel="stylesheet">
  {% block css %}


  <!-- Your stuff: Third-party CSS libraries go here -->

  <!-- This file stores project-specific CSS -->




  {% endblock %}

</head>

<body>
  <nav style="border-bottom: 1.5px solid #f6b2ca;border-radius: 45px;" class="navbar is-transaparent is-fixed-top has-padding-top-8 has-padding-bottom-8" role="navigation" aria-label="main navigation" id="navbar">
    <div class="container">
      <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'home' %}" style="font-size:1.4rem;text-transform: uppercase;letter-spacing: 1px;">
          <img src="{% static 'images/favicons/hoi-logo-new.png' %}"> &nbsp;Health Of India
        </a>
        <div id="navbarBurger" class="navbar-burger burger" data-target="navMenuDocumentation">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navMenuDocumentation" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Record
            </a>

            <div class="navbar-dropdown">
              <a href="{% url 'maps:oneshot_health_entry' %}" class="navbar-item">
                Record Your Health
              </a>
              <a href="{% url 'maps:health_entry' %}" class="navbar-item">
                Record A Help
              </a>
            </div>
          </div>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              Maps
            </a>

            <div class="navbar-dropdown">
              <a href="{% url 'maps' %}" class="navbar-item">
                Patient Map
              </a>
              <a href="{% url 'maps' %}" class="navbar-item">
                Grocery Map
              </a>
              <a href="{% url 'maps' %}" class="navbar-item">
                Medical Map
              </a>
              <a href="{% url 'maps' %}" class="navbar-item">
                Food Centers Map
              </a>
            </div>
          </div>


          <a href="{% url 'about' %}" class="navbar-item">
            About
          </a>
          <a href="{% url 'news:index' %}" class="navbar-item">
            COVID-19 News
          </a>
          <a href="/#pnm" class="navbar-item">
            Help Near Me
          </a>


        </div>
      </div>
    </div>
  </nav>

  <div class="">
    {% if messages %}
    {% for message in messages %}
    <div class="uk-alert-{% if message.tags %} {{ message.tags }} {% endif %}" uk-alert>
      <a class="uk-alert-close" uk-close></a>
      <p>{{ message }}</p>
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}
    <p>Use this document as a way to quick start any new project.</p>
    {% endblock content %}
  </div>
  <footer>
    {% include 'pages/footer.html' %}
  </footer>
  {% block modal %}{% endblock modal %}

  <!-- Le javascript
================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <!-- Bootstrap JS and its dependencies-->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- UIkit JS -->
  <script src="https://cdn.jsdelivr.net/npm/uikit@3.3.7/dist/js/uikit.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/uikit@3.3.7/dist/js/uikit-icons.min.js"></script>
  <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

  {% block javascript %}

  <!-- Your stuff: Third-party javascript libraries go here -->


  <!-- place project specific Javascript in this file -->

  {#  <script src="{% static 'js/project.js' %}"></script>#}


  {% endblock javascript %}
</body>

</html>