config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from fight_covid19.maps import views as map_views

urlpatterns = [
    path("", map_views.HomePageView, name="home"),
    path("maps/", include(("fight_covid19.maps.urls", "maps"), namespace="maps")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path("maps/", TemplateView.as_view(template_name="maps/maps.html"), name="maps"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("fight_covid19.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("news/", include(("fight_covid19.news.urls", "news"), namespace="news")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

fight_covid19/maps/urls.py
from django.urls import path
from fight_covid19.maps import views as map_views
from django.views.generic import TemplateView


urlpatterns = [
    path("", TemplateView.as_view(template_name="maps/maps.html"), name="home"),
    path("health_form/", map_views.HealthFormView, name="health_form"),
    path("map_markers/", map_views.MapMarkersView, name="map_markers"),
    path("my_health", map_views.MyHealthView, name="my_health"),
    path("patients_nearme", map_views.NearCount.as_view(), name="near_count"),
    path(
        "oneshot_health_entry",
        TemplateView.as_view(template_name="maps/one_shot_health_form.html"),
        name="oneshot_health_entry",
    ),
    path(
        "help_entry",
        TemplateView.as_view(template_name="maps/help_entry_form.html"),
        name="health_entry",
    ),
    path(
        "generate_unique_key",
        map_views.GenerateUniqueKey.as_view(),
        name="generate_unique_key",
    ),
    path(
        "oneshot_form_entry",
        map_views.OneShotFormEntry.as_view(),
        name="oneshot_form_entry",
    ),
]

fight_covid19/news/urls.py
from django.urls import path
from fight_covid19.news import views

urlpatterns = [
    path("", views.index, name="index"),
]

fight_covid19/users/urls.py
from django.urls import path

from fight_covid19.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

fight_covid19/maps/models.py
from django.db import models
from django.contrib.auth import get_user_model


class HealthEntry(models.Model):
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, null=True, blank=True
    )
    age = models.IntegerField(default=0)
    gender = models.CharField(
        choices=(("M", "Male"), ("F", "Female")), default="M", max_length=1,
    )
    fever = models.BooleanField(default=False)
    cough = models.BooleanField(default=False)
    difficult_breathing = models.BooleanField(default=False)
    self_quarantine = models.BooleanField(default=False)
    latitude = models.DecimalField(max_digits=18, decimal_places=15, null=True)
    longitude = models.DecimalField(max_digits=18, decimal_places=15, null=True)
    unique_id = models.CharField(null=True, blank=True, max_length=15)
    creation_timestamp = models.DateTimeField(auto_now_add=True, null=True, blank=True)


class KeyValuePair(models.Model):
    name = models.CharField(max_length=50)
    value = models.CharField(max_length=100)


class HelpEntry(models.Model):
    fullname = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15)
    help_type = models.CharField(
        choices=(
            ("food_donation", "Food Donation"),
            ("grocery_store", "Grocery Store"),
            ("medical_store", "Medical Store"),
            ("other", "Other"),
        ),
        default="food_donation",
        max_length=10,
    )
    address = models.CharField(max_length=150)
    description = models.TextField(null=True, blank=True)
    latitude = models.DecimalField(max_digits=18, decimal_places=15, null=True)
    longitude = models.DecimalField(max_digits=18, decimal_places=15, null=True)
    creation_timestamp = models.DateTimeField(auto_now_add=True, null=True, blank=True)

fight_covid19/news/models.py
from django.db import models

# Create your models here.

fight_covid19/api/coronacases/views.py
from django.core.cache import cache
from rest_framework import viewsets
from rest_framework.response import Response

from fight_covid19.maps.helpers import get_covid19_stats


class CoronaVirusCasesViewSet(viewsets.ViewSet):
    def list(self, request, *args, **kwargs):
        covid19_stats = cache.get("covid19_stats", default=None)
        if not covid19_stats:
            covid19_stats = get_covid19_stats()
        return Response(covid19_stats)

fight_covid19/api/hoi/views.py
import datetime

from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.db import transaction
from django.utils import timezone
from rest_framework import viewsets
from rest_framework.response import Response

from fight_covid19.maps.helpers import get_hoi_stats
from fight_covid19.maps.models import HealthEntry
from .serializers import HealthEntrySerializer, HealthEntryFormSerializer

User = get_user_model()


class HealthEntryViewSet(viewsets.ModelViewSet):
    """API endpoints for the Health Entry Statistics"""

    queryset = HealthEntry.objects.all()
    serializer_class = HealthEntrySerializer

    def create(self, request, *args, **kwargs):
        entryform_serializer = HealthEntryFormSerializer(
            data=request.data, context={"request": request}
        )
        if entryform_serializer.is_valid():
            try:
                # Atomic transaction
                with transaction.atomic():
                    entry_form = entryform_serializer.save()
                    entry_form.creation_timestamp = datetime.datetime.now(
                        tz=timezone.utc
                    )
                    entry_form.save()
            except Exception as e:
                return Response({"error": str(e)})
            resp = HealthEntrySerializer(entry_form)
            return Response(resp.data)

            # If there are errors, return them
        else:
            errors = dict()
            entryform_serializer.is_valid()
            errors.update(dict(entryform_serializer.errors))
            return Response(errors)


class HealthStatisticsViewSet(viewsets.ViewSet):
    def list(self, request, *args, **kwargs):
        hoi_stats = cache.get("hoi_stats", default=None)
        if not hoi_stats:
            hoi_stats = get_hoi_stats()
        return Response(hoi_stats)

fight_covid19/api/news/views.py
from django.core.cache import cache
from rest_framework import viewsets
from rest_framework.response import Response

from fight_covid19.news.helpers import get_news


class NewsViewSet(viewsets.ViewSet):
    def list(self, request, *args, **kwargs):
        news_dict = cache.get("news", default=None)
        if not news_dict:
            news_dict = get_news()
        return Response(news_dict)

fight_covid19/api/users/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from fight_covid19.api.users.serializers import UserSerializer

User = get_user_model()


class UserViewSet(viewsets.ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"
    # def get_queryset(self, *args, **kwargs):
    #     return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

    @action(detail=False, methods=["GET"])
    def current_user(self, request):
        try:
            user_query = User.objects.all().get(user=request.user)
            serialized_user = UserSerializer(user_query, context={"request": request})
        except:
            serialized_user = UserSerializer(request.user, context={"request": request})
        return Response(serialized_user.data)

fight_covid19/maps/api/views.py
import datetime

from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.db import transaction
from django.utils import timezone
from rest_framework import viewsets
from rest_framework.response import Response

from fight_covid19.maps.helpers import get_covid19_stats, get_hoi_stats
from fight_covid19.maps.models import HealthEntry
from .serializers import HealthEntrySerializer, HealthEntryFormSerializer

User = get_user_model()


class HealthEntryViewSet(viewsets.ModelViewSet):
    """API endpoints for the Health Entry Statistics"""

    queryset = HealthEntry.objects.all()
    serializer_class = HealthEntrySerializer

    def create(self, request, format=None, *args, **kwargs):
        entryform_serializer = HealthEntryFormSerializer(
            data=request.data, context={"request": request}
        )
        if entryform_serializer.is_valid():
            try:
                # Atomic transaction
                with transaction.atomic():
                    entry_form = entryform_serializer.save()
                    entry_form.user = User.objects.get(pk=request.data["user_id"])
                    entry_form.creation_timestamp = datetime.datetime.now(
                        tz=timezone.utc
                    )
                    entry_form.save()
            except Exception as e:
                return Response({"error": str(e)})
            resp = HealthEntrySerializer(entry_form)
            return Response(resp.data)

            # If there are errors, return them
        else:
            errors = dict()
            HealthEntryFormSerializer.is_valid()
            errors.update(dict(HealthEntryFormSerializer.errors))
            return Response(errors)


class CoronaVirusCasesViewSet(viewsets.ViewSet):
    def list(self, request, *args, **kwargs):
        data = dict()
        covid19_stats = cache.get("covid19_stats", default=None)
        if not covid19_stats:
            covid19_stats = get_covid19_stats()
        data["total"] = covid19_stats["total_stats"]
        data["last_updated"] = covid19_stats["tests_performed"]
        data["statewise"] = covid19_stats["statewise"]
        return Response(data)


class HealthStatisticsViewSet(viewsets.ViewSet):
    def list(self, request, *args, **kwargs):
        hoi_stats = cache.get("hoi_stats", default=None)
        if not hoi_stats:
            hoi_stats = get_hoi_stats()
        return Response(hoi_stats)

fight_covid19/maps/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
import json
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic import View
from django.views.generic.edit import FormView
from django.db.models import Count
from geopy.geocoders import Nominatim

from fight_covid19.maps import forms
from fight_covid19.maps.helpers import (
    get_covid19_stats,
    get_hoi_stats,
    get_map_markers,
    get_range_coords,
)
from fight_covid19.maps.models import HealthEntry
from fight_covid19.maps.models import HelpEntry
from fight_covid19.maps.models import KeyValuePair


class HomePage(View):
    def get(self, request, *args, **kwargs):
        covid19_stats = cache.get("covid19_stats", default=None)
        hoi_stats = cache.get("hoi_stats", default=None)
        if not covid19_stats:
            covid19_stats = get_covid19_stats()
        if not hoi_stats:
            hoi_stats = get_hoi_stats()

        # else:
        #     total, statewise, last_updated = c
        return render(
            request,
            "pages/home.html",
            context={"covid19_stats": covid19_stats, "hoi_stats": hoi_stats},
        )


HomePageView = HomePage.as_view()


class HealthForm(LoginRequiredMixin, FormView):
    form_class = forms.HealthEntryForm
    template_name = "maps/health_form.html"
    success_url = reverse_lazy("maps:my_health")

    def form_valid(self, form):
        if form.is_valid():
            entry = form.save(commit=False)
            entry.user = self.request.user
            entry.save()

        return super().form_valid(form)


HealthFormView = HealthForm.as_view()


class MyHealth(LoginRequiredMixin, ListView):
    model = HealthEntry
    template_name = "maps/my_health.html"
    context_object_name = "entries"

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user).order_by(
            "-creation_timestamp"
        )


MyHealthView = MyHealth.as_view()


class MapMarkers(View):
    def get(self, request, *args, **kwargs):
        points_list = cache.get("map_markers", default=None)
        if not points_list:
            points_list = get_map_markers()
        return JsonResponse(points_list, safe=False)


MapMarkersView = MapMarkers.as_view()


class NearCount(View):
    def get(self, request, *args, **kwargs):
        ranges = get_range_coords(
            float(request.GET.get("latitude")),
            float(request.GET.get("longitude")),
            float(request.GET.get("distance", 5)),
        )

        total_count = (
            HealthEntry.objects.all()
            .filter(
                latitude__range=(ranges["min_lat"], ranges["max_lat"]),
                longitude__range=(ranges["min_lon"], ranges["max_lon"]),
            )
            .values("user_id")
            .annotate(total=Count("user_id"))
            .count()
        )

        """TO get the location of the people by coordinates"""
        geolocator = Nominatim(user_agent="Health of India")
        location = geolocator.reverse(
            "{0}, {1}".format(request.GET.get("latitude"), request.GET.get("longitude"))
        )
        address = location.address

        data = dict()
        data["address"] = address
        data["total"] = total_count
        return JsonResponse(data)


class GenerateUniqueKey(View):
    def get(self, request, *args, **kwargs):
        try:
            counter = KeyValuePair.objects.get(name="unique_key_counter")
        except KeyValuePair.DoesNotExist:
            counter = KeyValuePair.objects.create(name="unique_key_counter", value="1")

        unique_id = counter.value

        # Updating values
        counter.value = str(int(counter.value) + 1)
        counter.save()

        return JsonResponse({"id": unique_id})


class OneShotFormEntry(View):
    def post(self, request, *args, **kwargs):
        raw_data = request.body.decode("utf-8")
        form_data = json.loads(raw_data)
        HealthEntry.objects.create(
            age=form_data["age"],
            gender=form_data["gender"],
            fever=form_data["fever"],
            cough=form_data["cough"],
            difficult_breathing=form_data["difficult_breathing"],
            self_quarantine=form_data["quarantine"],
            latitude=form_data["latitude"],
            longitude=form_data["longitude"],
            unique_id=form_data["unique_id"],
        )
        return JsonResponse({"status": "success"})


class HelpEntryForm(View):
    def post(self, request, *args, **kwargs):
        raw_data = request.body.decode("utf-8")
        form_data = json.loads(raw_data)
        HelpEntry.objects.create(
            fullname=form_data["fullname"],
            phone_number=form_data["phone_number"],
            help_type=form_data["help_type"],
            address=form_data["address"],
            description=form_data["description"],
            latitude=form_data["latitude"],
            longitude=form_data["longitude"],
        )
        return JsonResponse({"status": "success"})

fight_covid19/news/views.py
from django.shortcuts import render
from newsapi import NewsApiClient
from django.core.cache import cache
from fight_covid19.news.helpers import get_news


def index(request):
    news_dict = cache.get("news", default=None)
    if not news_dict:
        news_dict = get_news()
    return render(request, "news/news.html", context={"news_dict": news_dict})

fight_covid19/templates/maps/health_form.html
{% extends "base.html" %}

{% load static i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Health Status Form" %}{% endblock %}


{% block content %}

  <h1>Health Status Form</h1>
  <p>Fill out the form with correct information.</p>
  <p id="status"></p>
  <button id="find-me" class="btn btn-primary">Know my location</button>
  <hr>
  <form method="POST" action="{% url 'maps:health_form' %}">
    {% csrf_token %}

    {{ form|crispy }}
    <button class="primaryAction btn btn-primary" type="submit">{% trans "Submit" %}</button>
  </form>

{% endblock %}

{% block javascript %}
  <script>
    function geoFindMe() {

      const latitude_field = document.querySelector('#id_latitude');
      const longitude_field = document.querySelector('#id_longitude');
      const status = document.querySelector('#status');

      function success(position) {
        const latitude = position.coords.latitude;
        const longitude = position.coords.longitude;

        latitude_field.value = latitude;
        longitude_field.value = longitude;
        status.textContent = 'Done. Thank You!';
      }

      function error() {
        status.textContent = 'Unable to retrieve your location';
      }

      if (!navigator.geolocation) {
        status.textContent = 'Geolocation is not supported by your browser';
      } else {
        status.textContent = 'Locating…';
        navigator.geolocation.getCurrentPosition(success, error);
      }

    }

    window.addEventListener('DOMContentLoaded', (event) => {
      geoFindMe();
    });

    document.querySelector('#find-me').addEventListener('click', geoFindMe);
  </script>
{% endblock %}

fight_covid19/templates/maps/help_entry_form.html
{% extends "base-uikit.html" %}

{% load static i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Health Status Form" %}{% endblock %}

{% load static %}
{% load humanize %}



{% block content %}
<style>
  .hideError{
    display: none;
  }
</style>
<div class="container is-fullhd">
  <div class="section">
    <h3 class="title is-3 has-padding-top-3">Help Entry Form</h3>
    <p class="subtitle is-info">Please fill this form with correct information.</p>
    <div class="columns is-variable is-1-mobile is-0-tablet is-3-desktop is-8-widescreen is-2-fullhd">
      <div class="column">

        <!-- Health entry form -->
        {% csrf_token %}
        {% verbatim %}
        <div id="vue-app">
          <div class="uk-form-horizontal uk-margin-large">

            <!-- Name -->
            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label">Name Of Help Provider</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <div class="control">
                    <input v-model="age1" name="" class="input is-fullwidth"  id="form-horizontal-text" type="text"
                      style="width: 330px">
                  </div>
                  <p class="hideError help is-danger" name="age-error">
                    Invalid Name
                  </p>
                </div>
              </div>
            </div>

            <!-- Phone -->
            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label">Phone Of Help Provider</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <div class="control">
                    <input v-model="age1" name="" class="input is-fullwidth"  id="form-horizontal-text" type="phone"
                      style="width: 330px">
                  </div>
                  <p class="hideError help is-danger" name="age-error">
                    Invalid Phone
                  </p>
                </div>
              </div>
            </div>

            <!-- Help Type -->
            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label">Type Of Help Providing</label>
              </div>
              <div class="field-body">
                <div class="field is-narrow">
                  <div class="control">
                    <div class="select is-info">
                      <select v-model="gender" class="uk-select" id="form-horizontal-select">
                        <option value="F">Food Donation</option>
                        <option value="M">Medical Store</option>
                        <option value="O">Grocery Store</option>
                        <option value="O">Other</option>
                      </select>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Address -->
            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label">Address Of Help Provider</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <div class="control">
                    <input v-model="age1" name="" class="input is-fullwidth"  id="form-horizontal-text" type="text"
                      style="width: 330px">
                  </div>
                  <p class="hideError help is-danger" name="age-error">
                    Invalid Age
                  </p>
                </div>
              </div>
            </div>

            <!-- Description -->
            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label">Description Of Help Provider</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <div class="control" style="width: 330px">
                    <textarea class="textarea has-fixed-size" placeholder="" rows="5"></textarea>
                  </div>
                  <p class="hideError help is-danger" name="age-error">
                    Invalid Age
                  </p>
                </div>
              </div>
            </div>



            <br>
            <div class="control">
              <p class="is-success">{{ form_status }}</p>
              <button v-bind:disabled="submit_disabled" v-on:click="submitForm"
                class="button is-info is-outlined has-margin-bottom-7 has-margin-left-1">Submit Now</button>
            </div>
          </div>
        </div>

        <br><br><br>
        {% endverbatim %}


      </div>



    </div>
  </div>
</div>



{% endblock %}

{% block javascript %}
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script>

  // Vue code
  var app = new Vue({
    el: "#vue-app",
    data: {
      age: 0,
      gender: "F",
      fever: false,
      cough: false,
      difficult_breathing: false,
      quarantine: false,
      form_status: "",
      submit_disabled: false,
    },
    methods: {
      submitForm: function (event) {
        var x = document.getElementsByName('ageField');
        var y = document.getElementsByName('age-error');
        if(app.age <= 0 || app.age >=150){
          console.log('Invalid age');
          x[0].classList.add('is-danger');
          y[0].classList.remove('hideError');
          return;
        }
        else{
          x[0].classList.remove('is-danger');
          y[0].classList.add('hideError');
        }
        if (navigator.geolocation) {
          // Geolocation works

          //Verify the incoming data

          // Disable Submit button
          this.submit_disabled = true;
          this.form_status = "Locating...(Check if you given this page permission for Location access, if it takes too long).";

          navigator.geolocation.getCurrentPosition(async function (position) {
            // We've received users current location
            // Note this variable wouldn't work inside this function scope
            const latitude = position.coords.latitude;
            const longitude = position.coords.longitude;
            app.form_status = "Location received. Thank you :)";

            // Collected information
            var form_data = {
              latitude: latitude,
              longitude: longitude,
              age: app.age,
              cough: app.cough,
              gender: app.gender,
              fever: app.fever,
              difficult_breathing: app.difficult_breathing,
              quarantine: app.quarantine,
              datetime: new Date()
            };

            // Generate or Fetch unique id for this device
            if ('unique_id' in localStorage) {
              form_data['unique_id'] = localStorage.getItem('unique_id');
            } else {
              form_data['unique_id'] = await fetch('/maps/generate_unique_key')
                .then((response) => {
                  return response.json();
                })
                .then((data) => {
                  return data.id;
                });
            }

            //Check for existing health entries & store it locally
            if ('health_entries' in localStorage) {
              var d = localStorage.getItem('health_entries');
              var existing_entries = JSON.parse(d);
            } else {
              existing_entries = [];
            }
            existing_entries.push(form_data);
            localStorage.setItem('health_entries', JSON.stringify(existing_entries));

            // Send data to the server to be saved.
            var csrf_token = document.getElementsByName("csrfmiddlewaretoken")[0].value;
            fetch('/maps/oneshot_form_entry', {
              method: 'POST',
              body: JSON.stringify(form_data),
              headers: {
                'X-CSRFToken': csrf_token
              }
            })
              .then((response) => {
                return response.json();
              })
              .then((data) => {
                if ('status' in data) {
                  app.form_status = "Form submitted. Thank you filling in your information. You'll be redirected to homepage in 5 seconds.";
                  setTimeout(() => {
                    window.location.href = "/"
                  }, 5000);
                } else {
                  app.form_status = "Something went wrong. We were unable to save your information. Please try again later."
                }
              });

          }, function () {
            this.form_status = "We were unable to access your location. Please allow us to access your location to complete the form."
            app.submit_disabled = false;
          });
        } else {
          // Geolocation not supported
          this.form_status = "Geolocation is not supported by your browser. You cannot fill this form."
          app.submit_disabled = false;
        }
      }
    }
  });

  function geoFindMe() {

    const latitude_field = document.querySelector('#id_latitude');
    const longitude_field = document.querySelector('#id_longitude');
    const status = document.querySelector('#status');

    function success(position) {
      const latitude = position.coords.latitude;
      const longitude = position.coords.longitude;

      latitude_field.value = latitude;
      longitude_field.value = longitude;
      status.textContent = 'Done. Thank You!';
    }

    function error() {
      status.textContent = 'Unable to retrieve your location';
    }

    if (!navigator.geolocation) {
      status.textContent = 'Geolocation is not supported by your browser';
    } else {
      status.textContent = 'Locating…';
      navigator.geolocation.getCurrentPosition(success, error);
    }

  }
</script>
{% endblock %}

fight_covid19/templates/maps/my_health.html
{% extends "base-uikit.html" %}

{% load static i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "List of Health Entries" %}{% endblock %}

{% block content %}
  <h1 class="uk-margin-top">My Health</h1>
  <div class="uk-margin">
  Look at maps to visualize health entry data.
  </div>
  <div class="uk-grid-small uk-child-width-auto" uk-grid>
    <div>
      <a href="{% url 'maps:home' %}" class="uk-button uk-button-secondary">See Maps</a>
    </div>
    <div>
      <a href="{% url 'news:index' %}" class="uk-button uk-button-secondary">News Board</a>
    </div>
  </div>

  <hr>

  <div class="uk-margin">
    <a href="{% url 'maps:health_form' %}">Record a new entry by clicking here.</a>
  </div>
  <table class="uk-table uk-table-small uk-table-divider">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Fever</th>
      <th scope="col">Cough</th>
      <th scope="col">Difficulty in Breathing</th>
      <th scope="col">Self Quarantine</th>
      <th scope="col">Location</th>
      <th scope="col">Date & Time</th>
    </tr>
    </thead>
    <tbody>
    {% for x in entries %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ x.fever }}</td>
        <td>{{ x.cough }}</td>
        <td>{{ x.difficult_breathing }}</td>
        <td>{{ x.self_quarantine }}</td>
        <td><b>Lat</b>: {{ x.latitude }}, <b>Long</b>: {{ x.longitude }}</td>
        <td>{{ x.creation_timestamp }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <div class="uk-margin-large"></div>
{% endblock %}